[
    {
        titulo = 'Camiseta Juventus 2018',
        precio = 170000,
        img = '/data/dybala.png',
        indumentaria = 'camisetas',
        genero = 'hombre',
        marca = 'adidas',
    },
    {
        titulo = 'Nike Hypervenom',
        precio = 230000,
        img = '/data/hypervenom.png',
        indumentaria = 'guayos',
        genero = 'hombre',
        marca = 'nike',
    },
    {
        titulo = 'Camiseta PSG 2018',
        precio = 180000,
        img = '/data/psg.png',
        indumentaria = 'camisetas',
        genero = 'hombre',
        marca = 'nike',
    },
    {
        titulo = 'Nike Hypervenom Phantom',
        precio = 260000,
        img = '/data/phantom.png',
        indumentaria = 'guayos',
        genero = 'hombre',
        marca = 'nike',
    },
    {
        titulo = 'Camiseta Bayer 2018',
        precio = 175000,
        img = '/data/bayer.png',
        indumentaria = 'camisetas',
        genero = 'hombre',
        marca = 'adidas',
    },
    {
        titulo = 'Puma Evopower',
        precio = 220000,
        img = '/data/evopower.png',
        indumentaria = 'guayos',
        genero = 'hombre',
        marca = 'puma',
    },
    {
        titulo = 'Camiseta Real Madrid 2018',
        precio = 185000,
        img = '/data/madrid.png',
        indumentaria = 'camisetas',
        genero = 'hombre',
        marca = 'adidas',
    },
    {
        titulo = 'Adidas Nemeziz',
        precio = 265000,
        img = '/data/nemeziz.png',
        indumentaria = 'guayos',
        genero = 'hombre',
        marca = 'adidas',
    },
    {
        titulo = 'Camiseta Alemania 1990',
        precio = 175000,
        img = '/data/alemania.png',
        indumentaria = 'camisetas',
        genero = 'hombre',
        marca = 'adidas',
    },
    {
        titulo = 'Nike Mercurial',
        precio = 170000,
        img = '/data/mercurial.png',
        indumentaria = 'futbol salafur',
        genero = 'hombre',
        marca = 'nike',
    },
    {
        titulo = 'Camiseta Colombia Femenina',
        precio = 235000,
        img = '/data/colombia.png',
        indumentaria = 'camisetas',
        genero = 'mujer',
        marca = 'adidas',
    },
    {
        titulo = 'Nike Hypervenom',
        precio = 290000,
        img = '/data/hypervenom_amarillo.png',
        indumentaria = 'guayos',
        genero = 'hombre',
        marca = 'adidas',
    },

]